### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [Esenthel/EsenthelEngine#1]
Would you like to add more error handling for return values from functions like the following?
- [pthread_cond_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_init.html "Initialize a condition variable.") ⇒ [Constructor for SyncEvent](https://github.com/Esenthel/EsenthelEngine/blob/f39c2aec6a6e6ab4b253a1f3495d39bdab3f4ff4/Engine/Source/Misc/Thread.cpp#L298)
- [pthread_mutex_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [Constructor for SyncLock](https://github.com/Esenthel/EsenthelEngine/blob/f39c2aec6a6e6ab4b253a1f3495d39bdab3f4ff4/Engine/Source/Misc/Thread.cpp#L183)

**Comment by GregSlazinski** [comment]
Thanks for pointing that out!
Fixed in: https://github.com/Esenthel/EsenthelEngine/commit/aed5f9a09b0ef6152e5825887bbeeeadfc0f4b4c
Please let me know if you see any other issues!

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by GregSlazinski** [comment]
I never used any dedicated tools for that. However when compiling for Apple platforms (using Clang) it displayed a bunch of warnings, and I've fixed all issues at that time.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by GregSlazinski** [comment]
yes, normally I do that (check return values), if you see some other ignored checks, let me know, I'm happy to fix

**Comment by elfring** [comment]
* How would you like to [adjust the software around remaining update candidates](https://github.com/Esenthel/EsenthelEngine/blob/aed5f9a09b0ef6152e5825887bbeeeadfc0f4b4c/Engine/Source/Misc/Thread.cpp#L239 "Update candidate: SyncLock::on()")?
* How will open issues be fixed in bundled software libraries?

**Comment by GregSlazinski** [comment]
Do you mean the 'pthread_mutex_lock'?
Please check https://pubs.opengroup.org/onlinepubs/7908799/xsh/pthread_mutex_lock.html
The only applicable error here is the EAGAIN
However, SyncLock::on is performance critical, and doing any extra checks will slow down performance, so I'm against doing that.

> How will open issues be fixed in bundled software libraries?
Please explain your question more, I don't understand the question.

**Comment by elfring** [comment]
>I've fixed it, for DEBUG builds only, …

I find [this information](https://github.com/Esenthel/EsenthelEngine/commit/e0947c85de7315efecb36414640b44e5c2d5a2c6 "More checks for pthread_mutex_lock()") questionable.


>Do you mean the external libraries in "ThirdPartyLibs" folder?

Yes (for example).

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?

**Comment by GregSlazinski** [comment]
What's questionable?

**Comment by elfring** [comment]
Return values from the POSIX (thread) programming interface should be checked.
A failed lock call is undesirable also for production builds of your software, isn't it?

-----

How do you think about to [work with classes like “std::lock_guard” or “std::scoped_lock”](https://en.cppreference.com/w/cpp/thread "Description for C++ thread support library") instead?

**Comment by GregSlazinski** [comment]
It shouldn't fail if the code was written properly.
To test proper codes, DEBUG build can be used.
Enabling this in RELEASE would slow things down, so I am against it.

For helper classes please see SyncLocker / SyncLockerEx

**Comment by elfring** [comment]
>Enabling this in RELEASE would slow things down, so I am against it.

This view reduces the desired software correctness.
