### ISSUE TITLE
Engine no longer runs in Windows 8

### ISSUE THREAD

**Issue by webnetweaver** [Esenthel/EsenthelEngine#10]
Recent update is making this engine no longer work for Windows 8. The previous version worked fine until I upgraded earlier today. Now, when I try to run the editor, I get errors about missing dll files. I'm not updating to Windows 10 and I really shouldn't have to scour the internet to find a bunch of dll files(Xaudio2_9.dll). The system should either fallback to previous implementations or automatically detect and ask the user permission to install required dlls.

**Comment by GregSlazinski** [comment]
https://esenthel.com/forum/showthread.php?tid=9755&pid=56743#pid56743

**Comment by webnetweaver** [comment]
I do not see "#define SUPPORT_WINDOWS_7" in \Bin\EsenthelEngine\_\headers.h.  Should I add "#define SUPPORT_WINDOWS_7 1" to it?  Do I need to recompile the engine afterward?

**Comment by GregSlazinski** [comment]
https://github.com/Esenthel/EsenthelEngine/blob/master/Engine/H/_/headers.h
