### ISSUE TITLE
Instanced Rendering?

### ISSUE THREAD

**Issue by Brouilles** [Esenthel/EsenthelEngine#12]
Hi, 
I have a question. The engine support Instancing for same 3D mesh? Because I have in my game a large forest. And the FPS are very low. Maybe I have made a mistake. Not configured correctly for instacing models.

Thanks.

**Comment by GregSlazinski** [comment]
Yes instancing is used automatically.
Keep tri count low and minimize use of different materials per mesh. Also set LOD

**Comment by Brouilles** [comment]
Thanks :)

**Comment by GregSlazinski** [comment]
Also instancing is disabled if mesh has any skeleton bones / Vtx skinning
