### ISSUE TITLE
new update compilation failure. pthread_gettid_np is undeclared identifier

### ISSUE THREAD

**Issue by debugery** [Esenthel/EsenthelEngine#147]
it seems that _np means "not portable"

**Comment by debugery** [comment]
probably you need to save ret value of gettid() syscall in your own thread structure just after creation.

**Comment by debugery** [comment]
probably there is no way other than gettid() syscall

**Comment by debugery** [comment]
also setname and setaffinity are affected but i have some of them on this platform. replacing them also is simple.

**Comment by GregSlazinski** [comment]
I've created main issue for this here: https://github.com/Esenthel/EsenthelEngine/issues/152
