### ISSUE TITLE
Remove DIRECT_SOUND in profit of XAUDIO 2

### ISSUE THREAD

**Issue by Brouilles** [Esenthel/EsenthelEngine#15]
Hi, 
I propose to remove the Direct Sound support in profit of XAudio 2. Because Direct Sound is now deprecated by Microsoft. And Only Windows 8/8.1 and 10 are now officially supported (and soon only 10). I'm also for the remove of WINDOWS_OLD code (see https://store.steampowered.com/hwsurvey). In order to simplify the code.

I can make a PR if you are agree.
I plan in the coming weeks to integrate `Metal 2` and `AVAudioEngine` because OpenGL and OpenAL are now deprecated since macOS Mojave and Catalina. And will be deleted in the future.

At the end, we have (for desktop):
- Windows : DirectX 11 & XAudio 2
- macOS : Metal 2 & AVAudioEngine
- Linux : OpenGL & OpenAL

Have a good day.
Thanks.

**Comment by GregSlazinski** [comment]
Thank you for your activity.

Direct Sound allows for support of Win7, perhaps there are still some people who want to use it.
Direct Sound codes aren't big and don't make the engine messy at all.
Sometimes it's good to have an alternative sound processing codes, for example if there would be some crashes with XAudio, we could switch to DirectSound for testing and narrowing down the problem.

Actually WINDOWS_OLD is very needed, it stands for Win32 API. While WINDOWS_NEW for UWP.
WINDOWS_OLD generates EXE / DLL files, and WINDOWS_NEW UWP.
Both are used by the engine.

Metal support would be great, but I know it will be a lot of work, so good luck :)

Alternative is to add Vulkan (that runs natively on Win/Android/Linux), while on Mac it can be used together with https://github.com/KhronosGroup/MoltenVK (MoltenVK is free and allows to run Vulkan code on top of Metal)

**Comment by Brouilles** [comment]
XAudio is not available on Windows 7 with the June SDK of DirectX? But maybe not natively, I understand your point of view. Ok for WINDOWS_OLD. I have misunderstand this feature, I thought it was only for Windows XP and Vista support (see Windows 7 to a lesser extent). But not Win32 in general. Sorry!

What you think about x32 bits support? macOS Have dropped it, Linux Ubuntu in part. You think it's always necessary today? It's preferable today to turn to ARM (already supported in the engine, good job!).

Like you want for Metal. Many engines effectively turns to Vulkan and MoltenVK and dropped DirectX support (for PC, of course for Xbox & UWP in general, no choice). In order to have only one rendering cross-platform code. But I maintain AVAudioEngine because I think OpenAL can be removed in a near futur by Apple (I don't know if not already the case for iOS). 

In all cases, thanks for your precisions.
