### ISSUE TITLE
new BSTree compilation failure under clang

### ISSUE THREAD

**Issue by debugery** [Esenthel/EsenthelEngine#150]
https://stackoverflow.com/questions/17598699/error-in-unused-template-method/17599026
might be such problem

**Comment by GregSlazinski** [comment]
This fixed on Android - https://github.com/Esenthel/EsenthelEngine/commit/c17900aa6063523741669e6e742b7bd8adce5adf
Please try latest version

**Comment by debugery** [comment]
still compilation fails. after this fix i have many undefined refrences to new trees functions in Mesh_Simplify.cpp. maybe you need to compile it with clang yourself.

**Comment by GregSlazinski** [comment]
I have tried on Android, Linux Clang v12 and Mac Clang v14, works good.

**Comment by debugery** [comment]
here clang 15.0.7, also anything else latest possible stable complete versions like mature linux distros.

undefined references to:
EE::_WAVLRemove()
EE::_WAVLInsert()
EE::TreeNode::prev()
all inside Mesh_Simplify.cpp

**Comment by GregSlazinski** [comment]
Oh, that's not a compilation issue, that's a linker issue.
Fixed - https://github.com/Esenthel/EsenthelEngine/commit/b504cf9261a4ac0d0d6b5fe81476b8ac8d4a17c3

**Comment by debugery** [comment]
thanks. yes, but i thought that may new clang be effective on template bcause of prev template problem but one of them is not template anyways. so this was a separate issue.
