### ISSUE TITLE
blocky shadows at angle

### ISSUE THREAD

**Issue by veksha** [Esenthel/EsenthelEngine#154]
Hi, Greg.
when i'm looking at the shadow at an angle, it becomes blocky.
Is it a bug or am i missing something?

video:

https://github.com/Esenthel/EsenthelEngine/assets/275333/96ab54c1-d14f-4c71-a568-eb567dfd70eb

**Comment by GregSlazinski** [comment]
Hello,
The Editor will auto adjust shadow range based on camera orientation.
