### ISSUE TITLE
Enhancement: Enhance Usability by Adding "Close" Option via Right-click on Code Document Tabs

### ISSUE THREAD

**Issue by RednibCoding** [Esenthel/EsenthelEngine#163]
**Current Behavior:**
When a code document is selected from the left tree navigation, it opens in the editor view as a new tab. To close the tab, users currently need to navigate back to the tree, locate the document, and click on it.

**Suggested Enhancement:**
To streamline the user experience and enhance usability:

1. Allow users to right-click the tab in which the code document is opened to close it
or:
2. Add a small "x"-Button on the right side of the tab to close the tab.

**Rationale:**
By enabling this feature, users can manage their open documents more efficiently, eliminating the need to repeatedly navigate the tree to close a tab. This adjustment would likely speed up the workflow and make the editor more intuitive.

**Comment by GregSlazinski** [comment]
Just use middle-click to close (it's standard across the Editor to close stuff under mouse cursor with middle click)
also keyboard shortcut Alt+F3 (shortcuts can be seen on the bottom of the screen in the menu)
