### ISSUE TITLE
Feature: "onResize" Callback for Window Class

### ISSUE THREAD

**Issue by RednibCoding** [Esenthel/EsenthelEngine#166]
**Description:**
I'd like to propose an enhancement to the Window class. It would be beneficial to have an onResize callback function that allows developers to pass a callback to be executed when the window is resized.

**Expected Behavior:**
1. The onResize callback should be triggered whenever the window gets resized.
2. The callback function should receive the sender that called the callback (the window) and the delta width and height — that is, the difference between the dimensions before and after the resize event.
3. This function should be called once the resizing has been completed. Maybe `onAfterResize` would be a better name?

**Use Case:**
Having such a callback function would make it easier for developers to handle and respond to window resize events, especially when certain UI elements or layouts are sensitive to window dimensions.

**Example Usage**
```cpp
void myOnResizeHandler(window* sender, flt deltaWidth, flt deltaHeight)
{
  // Todo: handle the resize event
}
...
...
myWindow.onResize(myOnResizeHandler);
```

**Comment by GregSlazinski** [comment]
Just do like this:

```
   virtual OptionsClass& rect(C Rect &rect)override
   {
      super.rect(rect);
      // here resize sub elemenets
   }
```
