### ISSUE TITLE
class "EE::MemcThreadSafe<TaskBase *>" has no member "popFirst"	

### ISSUE THREAD

**Issue by Brouilles** [Esenthel/EsenthelEngine#17]
Hi, 
When I try to compiled the main branch, I get this error: `class "EE::MemcThreadSafe<TaskBase *>" has no member "popFirst"`. If I use `lockedPopFirst` it seems good. In *Esenthel Builder.cpp* at `if(TaskBase *t=Todo.lockedPopFirst())t->call();`.

**Comment by GregSlazinski** [comment]
Thanks for letting me know!
Fixed here:
https://github.com/Esenthel/EsenthelEngine/commit/3647be8976b7cb38c27e1dfecb29b02ac6f5b2dd
