### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [Esenthel/EsenthelEngine#2]
I suggest to reuse a higher level build system so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/ "Building software with CMake")
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction "Building software with Autoconf")

**Comment by GregSlazinski** [comment]
What do you mean by "powerful checks for software features"?

**Comment by elfring** [comment]
- Does [a tool like “autoscan”](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
- How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.14/manual/cmake-generators.7.html#cmake-generators "Listing of CMake generators")?

**Comment by GregSlazinski** [comment]
I don't see autoscan to be useful here, engine already has everything ready to be compiled, for Win/Web/Mac/Linux/Android etc.
Adding more stuff will make things more complicated and more difficult to maintain.
I don't see the need of other dev environments as the default standard dev env's are already supported - MSVS on Windows, Xcode on Mac, and for Linux I've chosen NetBeans.
Generally if there's some extra build option you'd like to see in Esenthel, then I would recommend it being added into the Esenthel Builder tool - https://github.com/Esenthel/EsenthelEngine/blob/master/Project/Source/Esenthel%20Builder.cpp

**Comment by elfring** [comment]
Do you care for [out-of-source builds](https://gitlab.kitware.com/cmake/community/wikis/FAQ#what-is-an-out-of-source-build "What is an out-of-source build?")?
