### ISSUE TITLE
Build system with CMake

### ISSUE THREAD

**Issue by Brouilles** [Esenthel/EsenthelEngine#20]
Why not refactor the build system with CMake?
It's seems more flexible. And allow developers to use the same IDE (CLion for exemple) across platforms.

Thanks.

**Comment by GregSlazinski** [comment]
The reason, is that I would have to learn CMake, and then convert projects to it, and then keep maintaining them. All of that would take a considerable amount of time.

**Comment by debugery** [comment]
you are currently doing 3x more work to maintain multiple build systems. that is cmake's job. learn just once and cmake will do the rest for you and also moves forward with new versions of build systems and lets you know if changes are required.

**Comment by FinnT730** [comment]
I think the main issue would be, that the way the engine has been created, would need to be recreated using CMAKE, which would take a long time, and for what? At the end of the day, it works right now.

**Comment by debugery** [comment]
CMake just manages those build systems for you, has nothing to do with the
way that engine has been created. You want work with almost all build
systems with less efforts? Just learn CMake.
https://usercontent.one/wp/cheatsheet.czutro.ch/wp-content/uploads/2020/09/CMake_Cheatsheet.pdf
For a fast start. Simple. A lot easier than managing those build systems
yourself.
