### ISSUE TITLE
Future for macOS Apple Silicon?

### ISSUE THREAD

**Issue by Brouilles** [Esenthel/EsenthelEngine#24]
Hi!
I want to know your future plan about macOS.
What are you planning? Support it (and so buy a new hardware)? Or deprecate the macOS support in the future?
And what are your decisions regarding the depression of OpenAL and OpenGL (and the non-real support of Vulkan outside of moltenvk)? And AVAudioEngine for Audio? And I don't talk about Ray Tracing and the OpenCL deprecation (I don't know if moltenvk support Vulkan Ray Tracing for macOS devices. Than Metal does).

I'm interesting about this! Personally, in my fork of Esenthel, I have removed macOS and iOS support. Because I don't need it and I don't have the means to endure everything.

Thanks!

**Comment by GregSlazinski** [comment]
I don't have any plans to drop Mac/iOS support, why?
I will keep them.
OpenGL is deprecated by Apple, but still works. I think it's the same story with OpenAL.
Vulkan would be cool but I don't have the time/finances for it at the moment.
In the future it's possible though I would recompile the engine to have native support for both x64 and Arm64. But for now I don't have any Mac Arm hardware to test it.
