### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Esenthel/EsenthelEngine#3]
I would like to point out that an identifier like “[`_GetBase`](https://github.com/Esenthel/EsenthelEngine/blob/f39c2aec6a6e6ab4b253a1f3495d39bdab3f4ff4/Engine/H/Misc/Misc.h#L54 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by GregSlazinski** [comment]
Esenthel uses many similar named functions like that and I don't intend to change that. This naming convention implies that it's a private function for the engine only not to be used by the user.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
