### ISSUE TITLE
Is Esenthel Incompatible with Windows 8.1?

### ISSUE THREAD

**Issue by Jillinger** [Esenthel/EsenthelEngine#31]
I downloaded Esenthel Engine, but cannot install it.
Whether I run Esenthel Builder, or Esenthel installer, I get the message ...
`This application can only run in the context of an app container`

Does Esenthel only work on Windows 10?

**Comment by GregSlazinski** [comment]
This error means that your OS is too old. You can either try installing all updates in windows 8 (check for updates) or upgrade to win10.

**Comment by Jillinger** [comment]
Okay. Thanks.
