### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by razvanab** [Esenthel/EsenthelEngine#32]
I get an error when i try to build the Apps \ Sample

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(2600,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\WindowsXaml\v16.0\Microsoft.Windows.UI.Xaml.Cpp.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\WindowsXaml\v16.0\Microsoft.Windows.UI.Xaml.Cpp.targets" is correct, and that the file exists on disk. [D:\stuff\Esenthel\Projects\_Build_\6 - Simple 3D\Project.vcxproj]
"

**Comment by GregSlazinski** [comment]
Hi there, most likely some Visual Studio components weren't installed.
Can you please make sure to install everything as specified in the docs:
https://esenthel.com/?id=doc#Compilers
