### ISSUE TITLE
Compilation issues for Arch Linux

### ISSUE THREAD

**Issue by CorruptedPlazma** [Esenthel/EsenthelEngine#33]
Hello, 

I took an interest in the engine for a school project, but I am having some problems getting the pre-built or compilation programs to run, the most common error at this point being a vague "Couldn't find valid GL Config". I believe this relates to OpenGL, but that is already fully functional on my system. I also cannot find a few of the dependencies, namely "libx" and others, I could find some, but they use different names on the Pacman repositories.

Any help to allow myself to use the engine on my system is greatly appreciated.

**Comment by GregSlazinski** [comment]
Hi,
There were some patches commited to the source version on GitHub, so if you've used binary from the esenthel website, try recompiling from source from github. If you still have problems you can reopen this issue.

**Comment by GregSlazinski** [comment]
You have to recompile the engine and builder from source code. Use make or NetBeans with C++ plugin

**Comment by GregSlazinski** [comment]
Alternatively you can use Windows version for now, and wait until Linux binary gets updated - that might take some time.
