### ISSUE TITLE
The current popcnt software implementation is not optimized

### ISSUE THREAD

**Issue by vohai2003** [Esenthel/EsenthelEngine#35]
I found out a way to optimize software implementation of popcnt:
int popcount(unsigned x)
{
    int c = 0;
    for (; x != 0; x &= x - 1)
        c++;
    return c;
}

**Comment by GregSlazinski** [comment]
Thanks a lot, I've commited, however there are even faster alternatives
https://github.com/Esenthel/EsenthelEngine/blob/development/Engine/Source/Misc/Misc.cpp#L793
But even they won't be used since there are HW implementations
