### ISSUE TITLE
Can't play on windows with Visual Studio 2022

### ISSUE THREAD

**Issue by karriszou** [Esenthel/EsenthelEngine#43]
EsenthelEngine looks very well, I regret having only discovered it now, so I want to try it and download EsenthelEngine binary, then open Tutorial project, when I click play button, following error occurs:

**C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(2643,3): error MSB4019: The imported project "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\WindowsXaml\v17.0\Microsoft.Windows.UI.Xaml.Cpp.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\WindowsXaml\v17.0\Microsoft.Windows.UI.Xaml.Cpp.targets" is correct, and that the file exists on disk.**

Can someone help me?

**Comment by GregSlazinski** [comment]
Please install VS components mentioned here:
https://esenthel.com/?id=doc#Compilers
That should solve the problem.
