### ISSUE TITLE
Default language 'en-150' is not valid

### ISSUE THREAD

**Issue by mokalux** [Esenthel/EsenthelEngine#46]
I was so hyped to try this engine but Engine Builder.exe failed with the error:

**C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.AppXPackage.Targets(6071,5): error APPX1685: Default language 'en-150' is not valid. For a list of supported values, see http://go.microsoft.com/fwlink/?LinkID=252020. [C:\Esenthel\xengine\Engine\Engine.vcxproj]**

Any clue how I could fix this?

Thanks

**Comment by mokalux** [comment]
EDIT: I checked only Compile Windows64 DX11 and that worked, ooray!

**Comment by GregSlazinski** [comment]
I checked entire engine repository but could not find anything that specifies en-150, maybe that's some bug in Visual Studio for UWP.
Yes it looks like it only affects UWP build, so you can safely use the normal / classic / win32 api build (recommended).
