### ISSUE TITLE
Application::active_wait issues

### ISSUE THREAD

**Issue by debugery** [Esenthel/EsenthelEngine#48]
- Mouse movement event makes this wait useless. In programs with a lot of mouse movements we have realtime updates (as much as mouse polling rate probably) and a lot unnecessary cpu usage. Please force mouse to respect this wait time.
- This wait time changes automatically. Mostly happens with openning more that one instances of the program and also happens when working with editor. I have a simple program here with 16 as wait time value and second instance sometimes somehow changes first instance's wait time to -1. I did not check if the value also is changed but  its behaviour is like -1 after that.
- It seems that the editor also is not prepared to properly use this feature and have unnecessary resource usage.
- It seems that the engine does not have frame cap so it is nice if you avoid intrrupting positive wait values with events or even better just make it choosable.
- Default value 0 does not help responsiveness. For a responsive program 1ms sleep seems better. Also sleep like operations are costy but better than 0.

**Comment by GregSlazinski** [comment]
That's the point to update when getting an event such as mouse move

**Comment by debugery** [comment]
- Yes but you are updating hundereds of unrelated gui objects with it. A lot cpu usage, depend on updates and callbacks cache misses, more ram usage, etc. I did not say that you ignore a mouse movement event but if there is a positive wait time then we need just that amount of responsiveness so just merge or queue those events and wait then update or separate it from the rest updates, etc.
- There are 4 other problems here too.

**Comment by GregSlazinski** [comment]
-so just merge or queue those events and wait then update or separate it from the rest updates, etc.
That sounds like complex thing that would not work well for everybody, but for some specific cases.
The current solution is simple and logical - there is an event, the app wakes up, so it can process the event.

"This wait time changes automatically." - I do not think this should happen, as these settings are per-app-instance.
If it does indeed happen, then it would have to be verified carefully, and could be a bug in either the OS or the engine codes.
However my initial guess is there's a different kind of problem which you should check your app codes first.

"It seems that the editor" I wrote the Editor before implementing active/background wait times, it does also background processing events, network synchronization, and data optimization, so at the moment it's not suitable for active/background wait times.

"It seems that the engine does not have frame cap"
It does not have a frame cap, it can use either v-sync (D.sync) or Time.wait, or App.active_wait / background wait.

Default value =0 means there is not wait.

**Comment by debugery** [comment]
More debugging is done about that wait changing bug:
- does not happen when no other esenthel program is running.
- value does not change after this behaviour which makes dumb recovery impossible.
- there is no way that my program do this.

so the bug is in your side. possibilities could be mistakes on named event object or similar ones.

**Comment by GregSlazinski** [comment]
The codes are here:
https://github.com/Esenthel/EsenthelEngine/blob/main/Engine/Source/Misc/Windows.cpp#L2024

You can debug if you'd like.

**Comment by debugery** [comment]
I tried to help but as long as active_wait does not change, I'm clueless. The only shared part that I could see is Atom but has no effect on active_wait and used SyncEvents.
Deeper investigation is required. You can easily reproduce this bug, just a simple app that update a counter on the screen and positive active_wait is enough. Run two instances of it or run it beside other esensel programs, one of them will face this bug sooner or later.

**Comment by debugery** [comment]
As workaround I will use
Time.wait(interval - Time.rd());
in my State's main Draw function which also will fix brutal evet wakeups.
Which one is better? wait in Draw or Update? I assume that there is no difference but you know better.

**Comment by debugery** [comment]
please don't change current implementation of event wakable active_wait/background_wait because Time.wait() works properly for frame cap and those two have thier own good usecases.

**Comment by debugery** [comment]
I disabled nvidia "allow flipping" option before and D.sync() without flipping makes micro stutters frequently. so i thought that maybe frame cap fix it and yes Time.wait makes less stutters but D.sync with flipping enabled is better (closer to D.freq() fps, more stable and less stutters).

**Comment by debugery** [comment]
what do you think about separating gui thread? multithread access to gpu data is slower but makes possible to have a gui system with different responsiveness. for a gui without animation or video rendering 4 fps is enough. very easy toimplement but
