### ISSUE TITLE
esenthel script macro preprocessor is broken

### ISSUE THREAD

**Issue by debugery** [Esenthel/EsenthelEngine#50]
Most of the times it just get removed from the produced c code. As a hacky workaround if you move that definition to a shared struct works but #ifdef like preprocessors does not work there too.

**Comment by GregSlazinski** [comment]
It will work fine if used inside a function code.
Everywhere else it's generally unsupported.
But you can do necessary stuff in a separate H header file and then include it in app properties.

**Comment by debugery** [comment]
so please make struct constructor a function call in your logic. without macro it's very hard to implement crossplatform code. #define works inside struct but #if and #ifdef just enables first one regardless of its condition. inside linux #ifdef WINDOWS is enabled.
second part of your answer works for now but separated external header files for hundereds of crossplatform structs is painful.
