### ISSUE TITLE
MusicPlayer/Playlist limits

### ISSUE THREAD

**Issue by debugery** [Esenthel/EsenthelEngine#51]
Please provide better access to internal Sound objects and their container.
- Acsses to configs like speed and frequency is required.
- Search is not possible just access through index is possible.
- prev/next does not work without history which is unnecessary and also gets duplicated records.

**Comment by GregSlazinski** [comment]
Speed not planned
Playlist has functions to get I-the song name/id
Music prev next work fine

**Comment by debugery** [comment]
By speed i did not mean that next/prev requires more performance. I need to search it and also have access to internal Sound object and a pointer to current Sound object. these are required:
- Pause
- Changing speed
- Changing freq
- Avoid string ops plus have a simple pointer instead of UID
etc
