### ISSUE TITLE
Poor OpenAL config

### ISSUE THREAD

**Issue by debugery** [Esenthel/EsenthelEngine#57]
OpenAL is feature rich and provides a good flexible config. Please provide high level access to them inside engine so no engine source code change or external config be required.

**Comment by GregSlazinski** [comment]
Open AL is just one of many sound APIs used depending on the platform. I don't provide direct api access because that would work for one platform only. Additionally you did not specify any particular feature.

**Comment by debugery** [comment]
required features:
- channel (mono, stereo, surround..., etc)
- default stereo mode is auto which auto selects between speakers and headphones which makes problems if both are attached.
- frequency (default value is 48000 hz but much better than this also is possible)
- rt-prio and its time limit (which is one part of your engine which uses rtkit)
- sources (max allocated sound sources, default is 256, in some situations different value is required).

etc.
https://github.com/kcat/openal-soft/blob/master/alsoftrc.sample
many of these has a lot effect on quality/resource usage. many games are tuning them properly.

**Comment by debugery** [comment]
as high level workaround, game could be published with openal config inside executable's dir but changing requires restart to take effect.

**Comment by debugery** [comment]
also per sound object config is not possible with this workaround
