### ISSUE TITLE
Map with Str/Char* key

### ISSUE THREAD

**Issue by debugery** [Esenthel/EsenthelEngine#58]
There is no Compare overload to handle Str keys. It works for example like:
Map<Str, Type> mBlah(CompareCS);
but I don't know how to do this for nested Maps like this without manual allocation or wrapping inside another struct:
Map<Str, Map<Str, Type>> mBlah;
I just tried to provide the overload myself but under linux clang there is an error about its address which i do not understand.
char* compare does not require to fill Str struct and is not hard to provide, you already have it in c standard library and that library is much faster than your own implementation.
You could at least remove that default initialization or just tell me how to do this please.
Sorry for this stupid problem.

**Comment by GregSlazinski** [comment]
For help in writing codes I recommend asking on the forum - https://esenthel.com/forum/

**Comment by debugery** [comment]
No it's about that unnecssary pre initialized argumet. Anyways workarounds are possible. Thank you for your time and attention.

**Comment by GregSlazinski** [comment]
It's not unnecssary, there's a ton of engine built-in 'Compare' functions, and because of that default value for the function parameter, in many cases you don't need to write ", Compare" manually.

**Comment by debugery** [comment]
So please provide Compare overloads for Char*/Char8*/Str, or we are forced to implement ourselves. Otherwise for mapping unknown dynamic data we need extra id provider and a map to dynamic reusable tokens.
also nested Map leads to dynamic memory allocations or wrapping internal Maps to structures with unnecessary constructor calls which is indeed the unnecessary part of the story.

**Comment by FinnT730** [comment]
Why not.... create an PR for all of this?

**Comment by GregSlazinski** [comment]
Can't create Compare overloads for Char*/Char8*/Str because it's unclear if programmer wants case-sensitive or not.
So you should specify manually CompareCI or CompareCS

**Comment by debugery** [comment]
for Str you could at least provide a default overload as CS then if CI be required we could change it later.
