### ISSUE TITLE
using some header only libraries is not possible in esenthel script

### ISSUE THREAD

**Issue by debugery** [Esenthel/EsenthelEngine#59]
as a clear example nuklear immediate mode gui header only library requires this for implementation:
#define NUKLEAR_IMPLEMENTATION
#include "nuklear.h"
inside one c file then the header where is required. Which is not easily possible in esenthel script.
This one is not required but you get the idea. please let us use header files inside of esenthel script then manage it how you want if is necessary.

**Comment by GregSlazinski** [comment]
You can write H header file with contents:
#define NUKLEAR_IMPLEMENTATION
#include "nuklear.h"

And then include that header file in double click application properties

**Comment by debugery** [comment]
The main problem is that this must be placed inside a c file once. Next possible way is to convert all those +15000 lines of code to esenthel script and fix macro preprocessor problems which is not sane. Next option is to work outside with that java ide requirement or just handle make and terminal myself but I miss your beatiful code editor and a gui library does not deserve this much so its features are completely ignored.

**Comment by GregSlazinski** [comment]
If it's an external library that has to be compiled first.
Then you can just compile it separately as a standalone library (*.lib / *.a)
And then include the header and library in double click application properties
