### ISSUE TITLE
Android NDK Version

### ISSUE THREAD

**Issue by BlackHornet** [Esenthel/EsenthelEngine#6]
Hi Grzegorz,

regarding your Extra docs:

> Min SDK required to run the app on Android:
> 
> Update all "Application.mk"
> APP_PLATFORM := android-18

I would suggest to use at least NDK r18b, because in r18 is a bug, that stack smashing protecting is not used when native sources are compiled for Android.
(see https://github.com/android-ndk/ndk/issues/815)

Kind regards

**Comment by GregSlazinski** [comment]
Hi BlackHornet, nice to see you again.

The APP_PLATFORM := android-18 does not specify the NDK release version, but the Minimum SDK version, which is:

> Jelly Bean | 4.3.x | API level 18

 https://source.android.com/setup/start/build-numbers
