### ISSUE TITLE
creating simple text based console programs in esenthel script pulls in extra dependencies

### ISSUE THREAD

**Issue by debugery** [Esenthel/EsenthelEngine#63]
Required APP_FLAGs are provided and application loop is avoided but still is not possible to turn off unnecessary parts of the engine like graphics and physics and avoid application data.
As example I need just a simple program that search a dir and list some absent requirements and report to an xml file and exit but the result is 40m executable file and 150m application data and 400m memory usage.

**Comment by GregSlazinski** [comment]
On Windows exe files are smaller.
You can turn off engine Pak data inclusion by double clicking app properties.
I've tested on windows but I don't think memory usage while in InitPre was anywhere near 400mb

**Comment by debugery** [comment]
Those numbers depends on hardware and kernel config like transparent hugepages, schedulers, memory compression, etc.
I have these problems:
- lzma is not configured properly, upx with different lzma handling compresses much better and it's loseless but after compression engine can't load embeded shaders anymore.
- App flags about no gpu and no x are not effective.
- With separated pak files, in app properties there is just one option to avoid shipping with project pak not disabling it.
- The other option is INIT() arguments which disables loading but errors comes up about loading main shader which is not required for my no gpu no x InitPre only program

so the only remained option is leaving esenthel script and editor and use your libs directly.
