### ISSUE TITLE
more control on esenthel script is required

### ISSUE THREAD

**Issue by debugery** [Esenthel/EsenthelEngine#64]
as example:
- custom CFLAGS/CXXFLAGS/LDFLAGS
- custom cpu extensions
- packer configs like parts size, file exclusion, etc
- custom application data dir
- selective required engine parts

**Comment by GregSlazinski** [comment]
Everything is already optimized for best case. If not then you need to be more specific.

**Comment by debugery** [comment]
Being specific:
- I need to change some debug flags, mitigations, stack size, string pool, strip/generate symbols, etc which you can not optimize for my requirements.
- I need to enable avx2 or any others which are not enabled because not all hardwares supports them and also i do not want them everywhere, maybe 2 separated executable for 2 different hardwares.
- I need to pack all assets except 4 images and 3 xml files because i need to download and change them based on events without redundants/leftovers/repacks.
- I need my pack files be multi part each part at most 2gb as example for disk fragmentation issues or specific loading plan. I need to put some data in some packs and others in other packs.
- Default Bin dir is not changable in esenthel script. I know that everything is binary but I need Data and Lib and inside of them more categories.
- I need to turn off all parts of the engine except your memory management, threading and dir listing for an specific task in a separate process because in that specific case multi processing is required.
- etc. Never ends. You can't optimize for a requirement that you do not know about.

**Comment by GregSlazinski** [comment]
What kind of debug flags / mitigations?
Stack size is set as 1 MB, it should be like that for all platforms, I found this value to be enough for most cases.
String Pool, at least on Windows is set to Share/Reuse, if that's not the case for other platforms, please let me know how to change that (what compiler flag) and I can apply.
Strip/remove symbols is done for Release, and NOT done for Debug.
AVX2 will be enabled for all platforms once majority of computers around the world will support them.
To disable some assets from being published please right click them and "Publishing\Disable"

As for all other requests, and (above if you need them to work differently):
-I try to keep the engine simple so it can work well for most cases.
Such specific customization, would either have to be applied on your side by yourself (via customization of your own engine version), or I could add some (but not all) as -paid- work only.

**Comment by debugery** [comment]
that approach about cpu extension is what i need you to avoid. we are a team of 2-4 dev with different hardwares. if you force enable avx2 or at future something like dx12 feature level 12 so 3 of us will be disabled.
instead a little textline and exporting env variables or just tunable make args is not that hard to implement.
anyways i still can export the project and have more control outside. i just thought that more flexibility inside the editor is nice for the engine to have.
