### ISSUE TITLE
esenthel editor can't create/edit simple text files

### ISSUE THREAD

**Issue by debugery** [Esenthel/EsenthelEngine#66]

**Comment by GregSlazinski** [comment]
For editing:
-you can create "Code" element and place it outside of "Application" element
-optionally edit code to have /* at the start to disable auto complete and stuff

For having an asset to be used as data that can be loaded inside the game,
drag and drop any *.txt or *.xml file to the project, and it should import as "binary" file which you can access using engine functions and classes

**Comment by debugery** [comment]
one usecase could be embedding my default xml config file and edit it inside the editor. but is avoidable. as you said i can create outside import as binary load as text file and read as xmldata but static change is headache.
