### ISSUE TITLE
CodeEditor (tabs)

### ISSUE THREAD

**Issue by SilverScreamBr** [Esenthel/EsenthelEngine#7]
please add a menu (tabs) or a list of open codes (like the one in notepad ++). This would make it much easier to use.

P.S .: this was written using traslate. I'm tired.

**Comment by webnetweaver** [comment]
Recent update is making this engine no longer work for Windows 8.  The previous version worked fine until I upgraded earlier today.  Now, when I try to run the editor, I get errors about missing dll files.  I'm not updating to Windows 10 and I really shouldn't have to scour the internet to find a bunch of dll files(Xaudio2_9.dll).  The system should either fallback to previous implementations or automatically detect and ask the user permission to install required dlls.

**Comment by GregSlazinski** [comment]
This is now available! Thanks :)
