### ISSUE TITLE
checking visibility of GuiObjs

### ISSUE THREAD

**Issue by debugery** [Esenthel/EsenthelEngine#76]
just like Window or other similar gui objects there is hide()/show() but visible() does not exist.
i'm trying to implement hud of my game so there is a lot of windowless gui objects on the screen. checking visibility of all of them at once through GuiObjs is required.

**Comment by debugery** [comment]
i understand that syncing with all child objects costs but it could be optional or you could queue visible/invisible objects and just check its length.

**Comment by GregSlazinski** [comment]
A function like that should be written manually because it's unclear if you want "any" or "all"

**Comment by debugery** [comment]
but Window is similar to GuiObjs and you already implementd this.
no problem. it's a simple flag at worst a simple list

**Comment by GregSlazinski** [comment]
Window is one object,
GuiObjs has many inside.

**Comment by debugery** [comment]
I don't know about internal implementation but Window has one or more child objects, Window as a single object is not usable. when Window is hidden all child also are hidden and you can check visibility. GuiObjs also has same hide/show but just checking is not implemented.
