### ISSUE TITLE
Regarding commit messages

### ISSUE THREAD

**Issue by rokups** [Esenthel/EsenthelEngine#8]
ok

**Comment by nem0** [comment]
ok

**Comment by amerkoleci** [comment]
ok

**Comment by GregSlazinski** [comment]
Hello and welcome! :)
Please ignore the "ok" and for latest changes and updates please visit official forum:
https://esenthel.com/forum/forumdisplay.php?fid=8

**Comment by rokups** [comment]
That is cool there is a changelog. Too bad you did not understand what i tried to say.

**Comment by nem0** [comment]
@rokups did you try to say there's a bug in the commit with commit message "ok"?

**Comment by rokups** [comment]
Spot on. Problem must be related to ok. These changes were most likely introduced because of ok and ok reasons trying to implement ok.
