### ISSUE TITLE
embedding project data/pak

### ISSUE THREAD

**Issue by debugery** [Esenthel/EsenthelEngine#82]
engine data is beautifully embeddable but there is no way to embed project data

**Comment by GregSlazinski** [comment]
Yes you can, just drag and drop all of your Data project elements to be located inside "Application" element 
(I'm talking about project view in the Editor on the left side)

**Comment by debugery** [comment]
so this is a bug, at least on linux even with no data steal one little Project.pak is created which contains some assets which i did not used.
maybe you forgot to include some new engine data so they are automatically pulled in as project data.

**Comment by debugery** [comment]
yes you just forgot "supported languages" data. please also add this to engine.pak

**Comment by debugery** [comment]
even if you disable this still one empty Bin dir is created
