### ISSUE TITLE
utf-8 support and overload for related functions

### ISSUE THREAD

**Issue by debugery** [Esenthel/EsenthelEngine#88]
I believe that Str8 should work but function overloads for like GetExt(Str8) does not exist. In Str for example I have 'ë' converted to 'Ã?' and a file with this name is not accessible.
Please peovide Str8 overload for such functions.

**Comment by GregSlazinski** [comment]
Engine functions work on Str UTF-16.
Str8 is treated as ASCII/ANSI only, not UTF8.

For manual conversions you can use:
Str  FromUTF8(CChar8 *text); // convert 'text' from UTF-8 format into Str
Str8 UTF8    (C Str  &text); // convert 'text' from   Str        into UTF-8 format

**Comment by debugery** [comment]
this approach is because of windows api 16bit wchar_t requirement which makes extra memory usage and conversion overhead.
if we use Str8 the only problem is unit size, most str operations are like ascii. isn't it better to fix Sr8 for it instead of conversions? as example utf-8 specific functions in Utf8? or better StrU8?

**Comment by debugery** [comment]
I also always had problems with winapi utf-8. winapi is also ok with char* utf-8, just showing in gui is problem if you create wmain/wWinMain, also Text wrappers exist. I never could fix this too.
