### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Brouilles** [Esenthel/EsenthelEngine#9]
Hi, 
Have you planned to change the licence? More open like MIT or BSD? Or proposed another licence who allow to create closed source for comercial projects? For example 500$ one time for ever (with no updates).

The Engine is production ready?
Thanks.

**Comment by GregSlazinski** [comment]
Hi and thanks for visiting.
You can already make closed source commercial games.
No need to pay for license, although donations are really appreciated, it's what keeps me going.
Yes it's production ready and super stable.

**Comment by Brouilles** [comment]
Thanks for your awnser @GregSlazinski 
I also talk about this `You may NOT resell or sub-license the source code to any third-party.`. I need to make many changes in the engine.  If I made a fork with several changes (closed source), the licence allow me to sell it?

**Comment by GregSlazinski** [comment]
You can sell games made with the engine. But you may not sell the source code of the engine.
You want to make a game or a game engine?

**Comment by Brouilles** [comment]
It's for a commercial purpose. We want to develop a game. But we need to make changes in the engine itself and don't want to make it Open Source. So create an internal fork for your purpose.

We are curently interested about Gamebryo and Tombstone Engine. Each other allow us to buy the engine and after this, fork it and modify it as we want. Any plan to do that with your engine?

**Comment by Brouilles** [comment]
We are not interested about Unity, Unreal or CryEngine because of the royalties.

**Comment by Brouilles** [comment]
And we are looking for a solution that would allow us to potentially sell our fork in the distant future.

**Comment by GregSlazinski** [comment]
> We want to develop a game. But we need to make changes in the engine itself and don't want to make it Open Source.

You don't have to make changes open source.

> And we are looking for a solution that would allow us to potentially sell our fork in the distant future.
No, that is specifically NOT allowed.

**Comment by Brouilles** [comment]
Thanks for your answers. We plan to use your engine as the basis.
We will surely make pull requests from our closed fork in the future in this repo.

**Comment by GregSlazinski** [comment]
I've relaxed some license requirements
