### ISSUE TITLE
deleting/exporting image from editor's image object

### ISSUE THREAD

**Issue by debugery** [Esenthel/EsenthelEngine#92]
for sharing screenshots in collaborative work i tried to create a fixed image object and exclude it from project.
it could be much better if we could delete/export its image.

**Comment by GregSlazinski** [comment]
You can delete and export an image by right-clicking on it

**Comment by debugery** [comment]
I need to keep the object itself so no reconfig for such excluded object be required. a key or button to clear it from inside is very simple and useful.
same problem exist for terrain "heightmap import", once it takes the images there is no way to clear them but automattically gets cleared on next engine start.
same problem exist for terrain material slots.
and probably other places.

for export, just one webp format is supported, don't know if is loseless, if be loseless a simple cnvertion is ok but a type combobox and export button inside the window is simple and useful.
