### ISSUE TITLE
Sound manager

### ISSUE THREAD

**Issue by debugery** [Esenthel/EsenthelEngine#98]
there is no sound manager and per sound config so
- a lot runtime disk io
- AI requires sound range, fade range, etc to think about reactions
- static 3D sound requires position (with editor static object class is possible but is not managable without manager)
- no per sound volume

etc

**Comment by GregSlazinski** [comment]
https://github.com/Esenthel/EsenthelEngine/blob/main/Engine/H/Sound/Sound.h

**Comment by debugery** [comment]
yes I'm currently working on this. these problems exist:
- there is no cache, I just see SoundPlayer object. Sound object is required. if you mean drag/drop and use the binary file's UID, I don't know why drag/drop does not work here, is just disabled, editor just rejects it (same thing happens on user differences but in this case there is no permission issue).
- after that problem I need per sound volume and range per sound object.
- after that problem there is no range, just a range scale but I don't know the base range to perform required calculations.

so i'm implementing my own wrapper struct around sound object and a simple manager and xml config to load it on game start.

**Comment by debugery** [comment]
- per sound volume is required for blending different sounds together nicely without editing that sound.
- per sound range is required for my AI system, on stimulus creation i need range and scale to see what characters could recieve it and how much attention is required.

these are possible inside code but there is no saved config per sound objects which leads to implementing a manager for them. something like sdlmixer in cryengine.
